name: Integration Tests
run-name: ${{ inputs.version }} - post release tests

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version'
        required: true
        type: string

jobs:
  Run_Tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Run Tests
        run: dotnet test --configuration Release --logger "trx;LogFilePrefix=test-results" --results-directory "./TestResults"
        continue-on-error: true
        env:
          TEST_DATA: ${{ secrets.TEST_DATA }}
          INTEGRATION_TEST_APIKEY: ${{ secrets.INTEGRATION_TEST_APIKEY }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: ${{ inputs.name }} Test Report
          path: ./TestResults/test-results*.trx
          reporter: dotnet-trx
      - name: Gather test results
        id: get-test-results
        run: |
          echo "passed=$(grep -oP '(?<=<UnitTestResult)[^<]*outcome="Passed"[^<]*(?=>)' ./TestResults/test-results*.trx | wc -l)" >> $GITHUB_OUTPUT
          echo "failed=$(grep -oP '(?<=<UnitTestResult)[^<]*outcome="Failed"[^<]*(?=>)' ./TestResults/test-results*.trx | wc -l)" >> $GITHUB_OUTPUT
          echo "skipped=$(grep -oP '(?<=<UnitTestResult)[^<]*outcome="Skipped"[^<]*(?=>)' ./TestResults/test-results*.trx | wc -l)" >> $GITHUB_OUTPUT
      - name: Update Test Summary Badge content
        uses: actions/github-script@v6
        with:
          script: |
              const gist = await github.rest.gists.get({
                  gist_id: '7c96c30e8017c8dfb57b88e323f8114b'
              })
              const gistContent = JSON.parse(gist.data.files['csharp-sdk-test-summary.json'].content)
              gistContent['message'] = `✓ ${{ steps.get-test-results.outputs.total }} | ✗ ${{ steps.get-test-results.outputs.total }} | → ${{ steps.get-test-results.outputs.total }}`
              await github.rest.gists.update({
                  gist_id: '7c96c30e8017c8dfb57b88e323f8114b',
                  files: {
                  'csharp-sdk-test-summary.json': {
                      content: JSON.stringify(gistContent)
                  }
                  }
              })
          github-token: ${{ secrets.GIST_SECRET }}

