name: Integration Tests
run-name: ${{ inputs.version }} - post release tests

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version'
        required: true
        type: string

jobs:
  Test_Chains:
    strategy:
      fail-fast: false
      matrix:
        chain: [Ethereum, Bitcoin, Polygon, Bsc, Harmony, Solana]
    name: Test Chain Packages
    uses: ./.github/workflows/integrationTests.yml
    with:
      name: ${{ matrix.chain }}
      version: ${{ inputs.version }}
    secrets: inherit
    
  Test_Other:
    if: ${{ always() }}
    strategy:
      fail-fast: false
      matrix:
        chain: [Nft, FungibleTokens, BlockchainFees]
    name: Test Other Packages
    uses: ./.github/workflows/integrationTests.yml
    with:
      name: ${{ matrix.chain }}
      version: ${{ inputs.version }}
    secrets: inherit
    needs: Test_Chains
