name: Prepare build package

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      ACTIONS_PACKAGE_SOURCE_PAT:
        required: true

jobs:
  preparePackage:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Add package source
        run: dotnet nuget add source --username tatumio --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/tatumio/index.json"
      - name: ${{ inputs.name }} - Restore dependencies
        run: dotnet restore ./Tatum.CSharp.${{ inputs.name }}/Tatum.CSharp.${{ inputs.name }}.csproj
      - name: ${{ inputs.name }} - Build
        run: dotnet build ./Tatum.CSharp.${{ inputs.name }}/Tatum.CSharp.${{ inputs.name }}.csproj --no-restore --configuration Release
      - name: ${{ inputs.name }} - Pack
        run: dotnet pack ./Tatum.CSharp.${{ inputs.name }}/Tatum.CSharp.${{ inputs.name }}.csproj --no-build --no-restore --configuration Release /p:Version=${{ inputs.version }}-build --output .
      - name: ${{ inputs.name }} - Push to Github Packages
        run: dotnet nuget push "./Tatum.CSharp.${{ inputs.name }}.${{ inputs.version }}-build.nupkg"  --api-key ${{secrets.ACTIONS_PACKAGE_SOURCE_PAT}} --source "github"